Django_Level_Four/learning_template/basic_app/urls.py
from django.urls import path
from basic_app import views


# TEMPLATE TAGGING
app_name = 'basic_app88'

urlpatterns = [
    path('other/',views.other,name='other'),
    path('base/',views.base,name='base'),
    path('relative/',views.relative, name="relative")
]

Django_Level_Four/learning_template/learning_template/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('basic_app/',include('basic_app.urls'))

    # path('other/',views.other,name='other'),
    # path('base/',views.base,name='base'),
    # path('relative/',views.relative, name="relative")

]

Django_Level_Four/learning_template/basic_app/models.py
from django.db import models

# Create your models here.

Django_Level_Four/learning_template/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def base(request):
    return render(request,'basic_app/base.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

Django_Level_Four/learning_template/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="navbar brand"><a href="{% url 'index'%}">Brand</a></li>
                <li class="navbar-link"><a href="{% url 'admin:index'%}">Admin</a></li>
                <li class="navbar-link"><a href="{% url 'basic_app88:other'%}">Other</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block%}
        <!-- Anything outside of this will be inherited if you extend! -->
        {% endblock %}
    </div>
</body>
</html>

Django_Level_Four/learning_template/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>WELCOME TO INDEX </h1>
    <h2>  {{ text | cut:'world'}}</h2>
    <h2>{{ number|add:"99" }}</h2>
    
    {% endblock %}


    

Django_Level_Four/learning_template/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>WELCOME TO OTHER </h1>
    <h2>this is a example of template inheritance</h2>
    {% endblock %}

Django_Level_Four/learning_template/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE_URL_TEMPLATE </h1>
    <a href="{% url 'basic_app88:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index'%}">Admin</a>
    <a href="{% url 'index' %}">Link to Index</a>
</body>
</html>